openapi: 3.0.2
info:
  version: '1.0'
  title: Employee Management Site Backend
  description: Open API specifications for ems backend APIs

paths:
  /admins/signup:
    post:
      summary: Admin Signup
      description: Signs up admin with specified properties
      tags:
        - Admins
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Admin"
                - type: object
                  properties:
                    secretKey:
                      type: string
                      example: my secret key
                  required:
                    - secretKey
      responses:
        201:
          description: Admin created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Admin"
        403:
          description: Forbidden, you did not provide correct `secretKey`
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /admins/login:
    post:
      summary: Admin Login
      description: Logins Admin and returns JWT token
      tags:
        - Admins
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  example: password
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: bearer
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        404:
          description: Admin not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        401:
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"

  /users/signup:
    post:
      summary: User Signup
      description: Signs up user with specified properties
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /users/login:
    post:
      summary: User Login
      description: Logins user and returns JWT token
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  example: password
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: bearer
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        401:
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
  /users/profile:
    get:
      summary: Get Current User
      description: Returns current logged in user
      tags:
        - Users
      security:
        - UserGuard: [ ]
      responses:
        200:
          description: User properties
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: You did not provide token or token is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /jobs:
    get:
      summary: Get All Jobs
      description: Returns all jobs
      tags:
        - Jobs
      responses:
        200:
          description: List of jobs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobsList"
    post:
      summary: Create Job
      description: Creates a new job with specified properties
      tags:
        - Jobs
      security:
        - AdminGuard: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/Job"
      responses:
        200:
          description: Created job
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /jobs/{jobId}:
    get:
      summary: Get Job
      description: Returns job with the specified `jobId`
      tags:
        - Jobs
      parameters:
        - $ref: "#/components/parameters/JobIdPathParam"
      responses:
        200:
          description: Job properties
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"
    delete:
      summary: Delete Job
      description: Deletes specified job with `jobId`
      tags:
        - Jobs
      security:
        - AdminGuard: [ ]
      parameters:
        - $ref: "#/components/parameters/JobIdPathParam"
      responses:
        200:
          description: Deleted job properties
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        404:
          description: Not found, did not found job with this id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /companies:
    get:
      summary: Get All Companies
      description: Returns all companies
      tags:
        - Companies
      responses:
        200:
          description: List of companies
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompaniesList"
    post:
      summary: Create Company
      description: Creates a new company with specified properties
      tags:
        - Companies
      security:
        - AdminGuard: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/Company"
      responses:
        200:
          description: Created company
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /companies/{companyId}:
    get:
      summary: Get Company
      description: Returns company with the specified `companyId`
      tags:
        - Companies
      parameters:
        - $ref: "#/components/parameters/CompanyIdPathParam"
      responses:
        200:
          description: Company properties
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
    delete:
      summary: Delete Company
      description: Deletes specified company with `companyId`
      tags:
        - Companies
      parameters:
        - $ref: "#/components/parameters/CompanyIdPathParam"
      security:
        - AdminGuard: [ ]
      responses:
        200:
          description: Deleted company properties
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        400:
          description: Bad request, you did not provide properties correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        404:
          description: Not found, did not found company with this id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"

components:
  securitySchemes:
    UserGuard:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: This API requires a valid JWT token
    AdminGuard:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: This API requires a valid JWT token
  parameters:
    UserIdPathParam:
      name: userId
      in: path
      description: User Id
      required: true
      schema:
        type: string
    JobIdPathParam:
      name: jobId
      in: path
      description: Job Id
      required: true
      schema:
        type: string
    CompanyIdPathParam:
      name: companyId
      in: path
      description: Company Id
      required: true
      schema:
        type: string
  schemas:
    Admin:
      type: object
      properties:
        id:
          type: string
          format: objectId
          example: 672b6ec43a791df2f93da42d
          readOnly: true
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          writeOnly: true
        name:
          type: string
          example: name
        superAdmin:
          type: boolean
          example: false
    User:
      type: object
      properties:
        id:
          type: string
          format: objectId
          example: 672b6ec43a791df2f93da42d
          readOnly: true
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          writeOnly: true
        firstName:
          type: string
          example: firstName
        lastName:
          type: string
          example: lastName
    UsersList:
      type: array
      description: List of Users
      items:
        $ref: "#/components/schemas/User"
    Job:
      type: object
      properties:
        id:
          type: string
          format: objectId
          example: 672b6ec43a791df2f93da42d
          readOnly: true
        title:
          type: string
          example: Web Developer
        description:
          type: string
          example: An experienced software developer is required
        companyId:
          type: string
          format: objectId
          example: 672b6ec43a791df2f93da42d
        creationDate:
          type: string
          format: date
          example: 2024-11-05T19:48:11.847Z
        expirationDate:
          type: string
          format: date
          example: 2024-11-05T19:48:11.847Z
    JobsList:
      type: array
      description: List of Jobs
      items:
        $ref: "#/components/schemas/Job"
    Company:
      type: object
      properties:
        id:
          type: string
          format: objectId
          example: 672b6ec43a791df2f93da42d
          readOnly: true
        name:
          type: string
          format: Company X
        description:
          type: string
          example: This company provides software security services
        logo:
          type: string
          example: https://www.google.com/image
    CompaniesList:
      type: array
      description: List of Companies
      items:
        $ref: "#/components/schemas/Company"
    Unauthorized:
      type: object
      properties:
        statusCode:
          type: number
          example: 401
        message:
          type: string
          example: Unauthorized
    Forbidden:
      type: object
      properties:
        statusCode:
          type: number
          example: 403
        message:
          type: string
          example: Forbidden
    BadRequest:
      type: object
      properties:
        statusCode:
          type: number
          example: 400
        message:
          type: array
          example:
            - Error Message 1
            - Error Message 2
        error:
          type: string
          example: Bad Request
    NotFound:
      type: object
      properties:
        statusCode:
          type: number
          example: 404
        message:
          type: string
          example: "*** not found"
        error:
          type: string
          example: Not Found
