version: "3.8"

services:
  ems-frontend:
    build: .
    container_name: Employee management site front-end
    environment:
      - APP_NAME=ems-frontend
    volumes:
      - /var/www/${APP_NAME}:/usr/app/build
    command: /bin/sh -c "mkdir -p /var/www/${APP_NAME} && cp -r /usr/app/build/* /var/www/${APP_NAME}/"
