services:
  backend:
    build: .
    container_name: ems-backend
    restart: always
    env_file:
      - .env.development
    environment:
      - PORT=${PORT:-3001}
    ports:
      - "${PORT}:${PORT}
